apiVersion: v1
kind: Service
metadata:
  name: auth-service             # auto generate env: SERVICE_NAME +  _SERVICE_HOST = AUTH_SERVICE_SERVICE_HOST
spec:
  selector:
    app: auth
  type: ClusterIP                # expose internal IP in cluster 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80